version: '3.3'

services:
  caro_project_be:
    build: .
    container_name: caro_project_be_rust
    ports:
      - '3001:3001'
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - default
